apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osticket.fullname" . }}-deployment
  labels:
    {{- include "osticket.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*.sh").AsConfig | indent 2 }}
