apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osticket.fullname" . }}-installer
  labels:
    {{- include "osticket.labels" . | nindent 4 }}
stringData:
    OST_NAME: "{{ .Values.ostName }}"
    OST_EMAIL: "{{ .Values.ostEmail }}"
    OST_ADMIN_FIRST_NAME: "{{ .Values.adminFirstName }}"
    OST_ADMIN_LAST_NAME: "{{ .Values.adminLastName }}"
    OST_ADMIN_EMAIL: "{{ .Values.adminEmail }}"
    OST_ADMIN_USERNAME: "{{ .Values.adminUsername }}"
    OST_ADMIN_PASSWORD: "{{ .Values.adminPassword }}"
    OST_TIMEZONE: "{{ .Values.timezone }}"
    RELEASE_NAME: "{{ include "osticket.fullname" . }}"
    MYSQL_ROOT_PASSWORD: "{{ .Values.mysql.auth.rootPassword }}"
    MYSQL_USER: "{{ .Values.mysql.auth.username }}"
    MYSQL_PASSWORD: "{{ .Values.mysql.auth.password }}"
    MYSQL_DB: "{{ .Values.mysql.auth.database }}"
    MYSQL_PRIMARY_PORT: "{{ .Values.mysql.primary.service.ports.mysql	}}"
    {{- if .Values.mysql.enabled }}
    {{- if eq .Values.mysql.architecture "replication" }}
    MYSQL_PRIMARY_HOST: "{{ .Release.Name }}-mysql-primary"
    OST_MYSQL_HOST: "{{ .Release.Name }}-mysql-primary:{{ .Values.mysql.primary.service.ports.mysql	}},{{ include "osticket.fullname" . }}-mysql-secondary:{{ .Values.mysql.primary.service.ports.mysql	}}"
    {{- else }}
    MYSQL_PRIMARY_HOST: "{{ .Release.Name }}-mysql"
    OST_MYSQL_HOST: "{{ .Release.Name }}-mysql"
    {{- end }}
    {{- else }}
    MYSQL_PRIMARY_HOST: "{{ .Values.mysql.externalAddress }}"
    OST_MYSQL_HOST: "{{.Values.mysql.externalAddress }}"
    {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osticket.fullname" . }}
  labels:
    {{- include "osticket.labels" . | nindent 4 }}
stringData:
  ost-config.php: |
    <?php
    if(!strcasecmp(basename($_SERVER['SCRIPT_NAME']),basename(__FILE__)) || !defined('INCLUDE_DIR'))
        die('kwaheri rafiki!');

    define('OSTINSTALLED',FALSE);
    if(OSTINSTALLED!=TRUE){
        if(!file_exists(ROOT_DIR.'setup/install.php')) die('Error: Contact system admin.'); //Something is really wrong!
        //Invoke the installer.
        header('Location: '.ROOT_PATH.'setup/install.php');
        exit;
    }
    define('SECRET_SALT','%CONFIG-SIRI');
    define('ADMIN_EMAIL','%ADMIN-EMAIL');
    define('DBTYPE','mysql');
    define('DBHOST','%CONFIG-DBHOST');
    define('DBNAME','%CONFIG-DBNAME');
    define('DBUSER','%CONFIG-DBUSER');
    define('DBPASS','%CONFIG-DBPASS');
    define('DBCONNECT_TIMEOUT', 3);
    define('TABLE_PREFIX','%CONFIG-PREFIX');
    define('TRUSTED_PROXIES', '*');
    define('LOCAL_NETWORKS', '127.0.0.0/24');
    define('SESSION_SESSID', 'OSTSESSID');

    {{- if or (eq .Values.mysql.architecture "replication") .Values.memcached.enabled }}    
    define('SESSION_BACKEND', 'memcache');
    define('MEMCACHE_SERVERS', '{{ include "osticket.fullname" . }}-memcached:{{ .Values.memcached.service.ports.memcached }}');
    {{- end }}
    ?>
