apiVersion: v2
name: osticket
description: The osTicket open source ticketing system packaged for Kubernetes.

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v1.18-2024040801"

dependencies:
  - name: mysql 
    version: "9.7.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled
  - name: memcached
    version: "6.3.14"
    repository: "https://charts.bitnami.com/bitnami"
    condition: memcached.enabled 
